# Generated by Django 3.1.1 on 2020-10-05 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hourly_rate_usd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='url_to_contract',
            field=models.URLField(null=True),
        ),
    ]
