# Generated by Django 3.1.1 on 2020-10-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201007_1652'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producerofsds',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='sds',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
