# Generated by Django 3.1.1 on 2020-10-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20201007_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='sds',
            name='file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
