# Generated by Django 3.1.1 on 2021-03-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210304_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='IgnoreDomains',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100)),
                ('reason', models.CharField(blank=True, max_length=250, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='sdsurlimport',
            options={'verbose_name': 'pdf_bulk_import_links'},
        ),
        migrations.AddField(
            model_name='sdsurlimport',
            name='is_downloaded',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sdsurlimport',
            name='is_duplicate',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='sdsurlimport',
            name='is_sds',
            field=models.BooleanField(null=True),
        ),
    ]
