# Generated by Django 3.1.1 on 2020-10-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sds_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sds',
            name='file',
            field=models.FileField(null=True, upload_to='pdf'),
        ),
    ]
