# Generated by Django 3.1.1 on 2021-03-06 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210306_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sdsurlimport',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
    ]
