# Generated by Django 3.1.1 on 2020-12-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201209_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sds_pdf_print_date',
            field=models.DateTimeField(blank=True, default='09.12.2020', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sds_pdf_revision_date',
            field=models.DateTimeField(blank=True, default='09.12.2020', null=True),
        ),
    ]
