# Generated by Django 3.1.1 on 2020-12-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201209_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sds_pdf_print_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sds_pdf_revision_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
