# Generated by Django 3.1.1 on 2021-03-06 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sdsurlimport_download_failed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IgnoreDomains',
            new_name='IgnoreDomain',
        ),
    ]
