# Generated by Django 3.1.1 on 2021-03-14 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210306_1347'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sdsurlimport',
            options={'verbose_name': 'PDF Bulk Import Link'},
        ),
        migrations.AlterField(
            model_name='sdsharvestsource',
            name='method',
            field=models.CharField(blank=True, choices=[('Scraping', 'Scraping'), ('Zip', 'Zip'), ('URL BULK', 'Url Bulk')], default='Zip', max_length=10),
        ),
        migrations.AlterField(
            model_name='sdsurlimport',
            name='language',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.language'),
        ),
    ]
