# Generated by Django 3.1.1 on 2020-12-09 15:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201209_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sds_pdf_print_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='sds_pdf_revision_date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
